name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      run: docker login --username=${{ secrets.DOCKER_USERNAME }}  registry.cn-hangzhou.aliyuncs.com  --password=${{ secrets.DOCKER_PASSWORD }} 
    - name: Build the Docker image
      run: make container-image
    - name: Push Docker image
      run: docker push registry.cn-hangzhou.aliyuncs.com/sunmd/kube-website:v1
