name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag qwertty01/kube-website:$(date +%s)  --build-arg HUGO_VERSION="0.97.0"
    - name: Docker login
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} 
    - name: Push Docker image
      run: docker push qwertty01/kube-website:$(date +%s)
