name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      run: docker login --username=${{ secrets.DOCKER_USERNAME }}  registry.cn-hangzhou.aliyuncs.com  --password=${{ secrets.DOCKER_PASSWORD }} 
    - name: Build the Docker image
      run: make container-image
    - name: Docker tag
      run: docker tag  gcr.io/k8s-staging-sig-docs/k8s-website-hugo:v0.87.0-7859bd25004b  registry.cn-hangzhou.aliyuncs.com/sunmd/kube-website:$(date +%s)
    - name: Push Docker image
      run: docker push qwertty01/kube-website:$(date +%s)
